In [1]:
# Importing the necessary libraries

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
# loading the dataset
dataset = pd.read_csv("House Price India.csv")

In [4]:
dataset

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14615,6762830250,42734,2,1.50,1556,20000,1.0,0,0,4,...,1957,0,122066,52.6191,-114.472,2250,17286,3,76,221700
14616,6762830339,42734,3,2.00,1680,7000,1.5,0,0,4,...,1968,0,122072,52.5075,-114.393,1540,7480,3,59,219200
14617,6762830618,42734,2,1.00,1070,6120,1.0,0,0,3,...,1962,0,122056,52.7289,-114.507,1130,6120,2,64,209000
14618,6762830709,42734,4,1.00,1030,6621,1.0,0,0,4,...,1955,0,122042,52.7157,-114.411,1420,6631,3,54,205000
14619,6762831463,42734,3,1.00,900,4770,1.0,0,0,3,...,1969,2009,122018,52.5338,-114.552,900,3480,2,55,146000

In [5]:
# DATA PREPROCESSING

# Check for missing values
dataset.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

In [6]:

# Drop the unnecessary column
X = dataset.drop('Price', axis=1)

In [7]:
# Convert the 'number of bedrooms' column to integer
dataset['number of bedrooms'] = dataset['number of bedrooms'].astype(int)

In [8]:
# Fill missing values with mean
dataset.fillna(dataset.mean(), inplace=True)

In [9]:
# Splitting the dataset
y = dataset['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
                    # ANN MODEL BUILDING

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()

model.add(layers.Dense(64, activation='relu', input_dim=X_train.shape[1]))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(1))

In [11]:

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mae'])

In [12]:
history = model.fit(X_train, y_train, validation_split=0.2, epochs=50, batch_size=32)

Epoch 1/50
293/293 [==============================] - 2s 3ms/step - loss: 386206009393152.0000 - mae: 6261100.0000 - val_loss: 126803902464.0000 - val_mae: 229272.8281
Epoch 2/50
293/293 [==============================] - 1s 2ms/step - loss: 149219737600.0000 - mae: 250699.7656 - val_loss: 129709473792.0000 - val_mae: 219948.7031
Epoch 3/50
293/293 [==============================] - 1s 2ms/step - loss: 163691151360.0000 - mae: 267923.6250 - val_loss: 138648469504.0000 - val_mae: 219300.6094
Epoch 4/50
293/293 [==============================] - 1s 2ms/step - loss: 217171935232.0000 - mae: 331101.7500 - val_loss: 136959442944.0000 - val_mae: 268678.6875
Epoch 5/50
293/293 [==============================] - 1s 3ms/step - loss: 250368114688.0000 - mae: 360181.7188 - val_loss: 130709094400.0000 - val_mae: 218767.7812
Epoch 6/50
293/293 [==============================] - 1s 3ms/step - loss: 307177750528.0000 - mae: 410978.2500 - val_loss: 300177948672.0000 - val_mae: 490720.1562
Epoch 7/50
293/293 [==============================] - 1s 4ms/step - loss: 427617124352.0000 - mae: 503436.6875 - val_loss: 203821481984.0000 - val_mae: 379550.0625
Epoch 8/50
293/293 [==============================] - 1s 3ms/step - loss: 555891163136.0000 - mae: 573714.1875 - val_loss: 1026228879360.0000 - val_mae: 977885.1875
Epoch 9/50
293/293 [==============================] - 1s 2ms/step - loss: 8140936970240.0000 - mae: 2044026.7500 - val_loss: 1006548090880.0000 - val_mae: 938284.3125
Epoch 10/50
293/293 [==============================] - 1s 2ms/step - loss: 9770020896768.0000 - mae: 2400114.2500 - val_loss: 21560893112320.0000 - val_mae: 4629781.5000
Epoch 11/50
293/293 [==============================] - 1s 2ms/step - loss: 9598177116160.0000 - mae: 2465585.5000 - val_loss: 630893641728.0000 - val_mae: 710593.1875
Epoch 12/50
293/293 [==============================] - 1s 2ms/step - loss: 11559038353408.0000 - mae: 2750104.2500 - val_loss: 313189072896.0000 - val_mae: 432854.1250
Epoch 13/50
293/293 [==============================] - 1s 2ms/step - loss: 9249881063424.0000 - mae: 2297706.2500 - val_loss: 13233267146752.0000 - val_mae: 3620420.5000
Epoch 14/50
293/293 [==============================] - 1s 2ms/step - loss: 9351036141568.0000 - mae: 2406742.0000 - val_loss: 288911818752.0000 - val_mae: 404032.0000
Epoch 15/50
293/293 [==============================] - 1s 2ms/step - loss: 9978608877568.0000 - mae: 2416578.5000 - val_loss: 18503432142848.0000 - val_mae: 4286937.5000
Epoch 16/50
293/293 [==============================] - 1s 2ms/step - loss: 7583499288576.0000 - mae: 2037599.5000 - val_loss: 7682140405760.0000 - val_mae: 2749980.5000
Epoch 17/50
293/293 [==============================] - 1s 2ms/step - loss: 11013556535296.0000 - mae: 2598598.2500 - val_loss: 156220522496.0000 - val_mae: 232495.6719
Epoch 18/50
293/293 [==============================] - 1s 2ms/step - loss: 8996259889152.0000 - mae: 2287490.2500 - val_loss: 14210788491264.0000 - val_mae: 3753054.0000
Epoch 19/50
293/293 [==============================] - 1s 2ms/step - loss: 8738455945216.0000 - mae: 2065903.3750 - val_loss: 16282182221824.0000 - val_mae: 4019567.2500
Epoch 20/50
293/293 [==============================] - 1s 2ms/step - loss: 8858879655936.0000 - mae: 2230249.5000 - val_loss: 7079834157056.0000 - val_mae: 2638782.2500
Epoch 21/50
293/293 [==============================] - 1s 2ms/step - loss: 8451526230016.0000 - mae: 2373939.7500 - val_loss: 3449668239360.0000 - val_mae: 1823319.1250
Epoch 22/50
293/293 [==============================] - 1s 2ms/step - loss: 11349950201856.0000 - mae: 2399984.0000 - val_loss: 1686414163968.0000 - val_mae: 1267847.2500
Epoch 23/50
293/293 [==============================] - 1s 3ms/step - loss: 6080092438528.0000 - mae: 1989518.0000 - val_loss: 2820401266688.0000 - val_mae: 1653179.3750
Epoch 24/50
293/293 [==============================] - 1s 3ms/step - loss: 8746307682304.0000 - mae: 2349438.5000 - val_loss: 12877805125632.0000 - val_mae: 3571095.7500
Epoch 25/50
293/293 [==============================] - 1s 3ms/step - loss: 7659374247936.0000 - mae: 2143482.2500 - val_loss: 19481120210944.0000 - val_mae: 4399560.5000
Epoch 26/50
293/293 [==============================] - 1s 3ms/step - loss: 8552783544320.0000 - mae: 2343238.0000 - val_loss: 1552651124736.0000 - val_mae: 1194885.7500
Epoch 27/50
293/293 [==============================] - 1s 2ms/step - loss: 8124416131072.0000 - mae: 2238964.5000 - val_loss: 3980955746304.0000 - val_mae: 1963708.8750
Epoch 28/50
293/293 [==============================] - 1s 2ms/step - loss: 6975324160000.0000 - mae: 2165152.0000 - val_loss: 6124599246848.0000 - val_mae: 2452336.2500
Epoch 29/50
293/293 [==============================] - 1s 2ms/step - loss: 8835115778048.0000 - mae: 2281027.7500 - val_loss: 767739953152.0000 - val_mae: 838202.8750
Epoch 30/50
293/293 [==============================] - 1s 2ms/step - loss: 7064969543680.0000 - mae: 2096560.5000 - val_loss: 731821768704.0000 - val_mae: 779214.1875
Epoch 31/50
293/293 [==============================] - 1s 2ms/step - loss: 6611292651520.0000 - mae: 1966978.3750 - val_loss: 991980945408.0000 - val_mae: 931330.4375
Epoch 32/50
293/293 [==============================] - 1s 2ms/step - loss: 8063338151936.0000 - mae: 2210626.0000 - val_loss: 2689383268352.0000 - val_mae: 1613458.2500
Epoch 33/50
293/293 [==============================] - 1s 2ms/step - loss: 8052200701952.0000 - mae: 2133848.5000 - val_loss: 284006416384.0000 - val_mae: 399553.7812
Epoch 34/50
293/293 [==============================] - 1s 2ms/step - loss: 6703220785152.0000 - mae: 1911832.7500 - val_loss: 1724686401536.0000 - val_mae: 1282874.3750
Epoch 35/50
293/293 [==============================] - 1s 2ms/step - loss: 6688972210176.0000 - mae: 2056727.8750 - val_loss: 865640710144.0000 - val_mae: 860924.6875
Epoch 36/50
293/293 [==============================] - 1s 2ms/step - loss: 7234954199040.0000 - mae: 2148726.2500 - val_loss: 20214326493184.0000 - val_mae: 4482179.5000
Epoch 37/50
293/293 [==============================] - 1s 2ms/step - loss: 6483089031168.0000 - mae: 2084782.6250 - val_loss: 3161467912192.0000 - val_mae: 1752795.5000
Epoch 38/50
293/293 [==============================] - 1s 2ms/step - loss: 7736186109952.0000 - mae: 2166528.7500 - val_loss: 579436609536.0000 - val_mae: 674621.5000
Epoch 39/50
293/293 [==============================] - 1s 2ms/step - loss: 6552245239808.0000 - mae: 2102089.2500 - val_loss: 27629090504704.0000 - val_mae: 5244501.5000
Epoch 40/50
293/293 [==============================] - 1s 2ms/step - loss: 6038249013248.0000 - mae: 1956632.3750 - val_loss: 9417608134656.0000 - val_mae: 3048503.5000
Epoch 41/50
293/293 [==============================] - 1s 3ms/step - loss: 6083767173120.0000 - mae: 2024574.7500 - val_loss: 7190149070848.0000 - val_mae: 2659631.7500
Epoch 42/50
293/293 [==============================] - 1s 3ms/step - loss: 7023575957504.0000 - mae: 2098500.0000 - val_loss: 6540472877056.0000 - val_mae: 2535234.5000
Epoch 43/50
293/293 [==============================] - 1s 3ms/step - loss: 6654122786816.0000 - mae: 1995656.8750 - val_loss: 125465509888.0000 - val_mae: 219114.8125
Epoch 44/50
293/293 [==============================] - 1s 3ms/step - loss: 6842843398144.0000 - mae: 2018347.1250 - val_loss: 363804884992.0000 - val_mae: 489614.1562
Epoch 45/50
293/293 [==============================] - 1s 2ms/step - loss: 5630823759872.0000 - mae: 1915904.5000 - val_loss: 525089472512.0000 - val_mae: 681276.8125
Epoch 46/50
293/293 [==============================] - 1s 2ms/step - loss: 6646905438208.0000 - mae: 2033458.5000 - val_loss: 6946935013376.0000 - val_mae: 2613778.5000
Epoch 47/50
293/293 [==============================] - 1s 2ms/step - loss: 6155274289152.0000 - mae: 1980587.1250 - val_loss: 1866778804224.0000 - val_mae: 1336751.7500
Epoch 48/50
293/293 [==============================] - 1s 2ms/step - loss: 5494333243392.0000 - mae: 1846960.2500 - val_loss: 3598686879744.0000 - val_mae: 1872652.7500
Epoch 49/50
293/293 [==============================] - 1s 2ms/step - loss: 6172002222080.0000 - mae: 2024556.1250 - val_loss: 129858879488.0000 - val_mae: 253849.8750
Epoch 50/50
293/293 [==============================] - 1s 2ms/step - loss: 5875436093440.0000 - mae: 1967145.7500 - val_loss: 123837063168.0000 - val_mae: 224524.9219

In [13]:
 # TEST THE MODEL

mse, mae = model.evaluate(X_test, y_test)
print("Mean Squared Error:", mse)
print("Mean Absolute Error:",mae)

92/92 [==============================] - 0s 2ms/step - loss: 137798451200.0000 - mae: 232353.2031
Mean Squared Error: 137798451200.0
Mean Absolute Error: 232353.203125